### ISSUE TITLE
Tasks and Nodes

### ISSUE THREAD

**Issue by oXis** [kprotty/zap#10]
Hi,

I'm trying to understand the code and I was wondering. What is the relation between a `Task` and a `Node`. I don't understand why tasks have nodes members. Is it because `Queue` and `Buffer` take `Node` structs instead of `Task`s?

What is the rationale behind that design choice? 

My understanding is as follows:
I see that in `async.zig` you create a wrapper around a `Task` with a `frame` member. Is wrapping tasks into our own structs the way to go to use your thread pool? And in that case, maybe it's why you are using `Node`s, because you cannot have knowledge of the "wrapping struct" when dealing with popping or pushing into `Queue`/`Buffer`.

I hope I'm clear... and sorry to dig up an old project of yours xD

**Comment by kprotty** [comment]
> Is wrapping tasks into our own structs the way to go to use your thread pool?

Yea, this is the core idea behind intrusive data structures. Queueing was written in a similar way so that it could be in its own file, with Task using Node intrusively.
