### ISSUE TITLE
Consider setting default branch to “blog” 

### ISSUE THREAD

**Issue by garettbass** [kprotty/zap#7]
When visiting the repo, I was initially browsing the default branch, “master”, but the “blog” branch is much more recent.  Promoting the “blog” branch to the default branch in the repository settings could improve discovery for new visitors.

Thanks for this implementation and detailed discussion in the blog article.

**Comment by kprotty** [comment]
I'm not sure if there's many new visitors, but thanks for the suggestion.

**Comment by kprotty** [comment]
Ended up doing it.
